anowell/are-we-learning-yet

_data/crates.yaml

[Faiss](https://github.com/facebookresearch/faiss) is Facebook AI Research's library for efficient similarity search and clustering of dense vectors. This crate provides safe high-level bindings to this library.

Add crate: faiss

---

index.html

Fixed a typo, added links, standardized punctuation.

Minor editing improvements to index.html.

---

_data/crates.yaml

resolves #29 
I added the crates.io names and a topic for each create. Can it be that easy? :)

Add crates: forester, openml, arff

---

index.html

I have added the link to the `science-and-ai` channel on Discord for people interested in getting in touch with the community.

Add Discord's channel

---

_data/crates.yaml

Add Peroxide to scientific-computing

Add crate: Peroxide

---

_data/crates.yaml

add blasoxide to crates.yaml

---

_data/crates.yaml

Add crate simplers_optimization for black box optimization.

Add crate simplers_optimization

---

_data/crates.yaml

Added crate:rettle

---

_data/crates.yaml

[Cogent](https://crates.io/crates/cogent) is an actively developed basic neural network library.

Add cogent library

---

_data/crates.yaml

See https://github.com/huggingface/tokenizers

Add crate tokenizers

---

_data/crates.yaml

Research Paper:- https://www.researchgate.net/publication/323424266_A_k_-Deviation_Density_Based_Clustering_Algorithm

Add crate: kddbscan

---

_data/crates.yaml

* `ndsparse` provides sparse structures for N-dimensions
* `mop` is a NP-Problem framework that is currently using a meta-heuristic solver

Add crates: ndsparse and mop

---

_data/crates.yaml

Hi! Could you please add SmartCore to http://www.arewelearningyet.com/? Thank you!

Adds SmartCore

---

_data/crates.yaml

Add neuronika

---

_data/crates.yaml

This crate solves for generalized linear models (including linear & logistic regression) on `ndarray` data.

Add crate: ndarray-glm

---

_data/crates.yaml

Please add crate to category: Clustering

Add crate: kmedoids

---

_data/crates.yaml

Replaces #87
I merely rebased @aidan-fitz's commit in that PR and fixed the topic tag so it would build.

Add finalfusion, rust2vec

---

.github/workflows/build.yml
README.md
_scraper/README.md

- Removed the custom build of cobalt from CI.
- Added some additional documentation to make it easier to get started contributing.

Update cobalt and more docs

---

_scraper/src/main.rs

Fixing lint that [broke build](https://github.com/anowell/are-we-learning-yet/actions/runs/1942666425)

Fixing clippy lint

---

_data/crates.yaml

Do I need to add anything else like links to github or crates.io?

Add dfdx to crates

---

_scraper/src/github.rs
_scraper/src/main.rs

`cargo clippy --fix && cargo fmt`

Fix warnings from latest clippy

---

_data/crates.yaml

Found two solid NLP crates (by different authors) for running LLMs.

Update crates.yaml to include two high-level llm crates

---

_data/crates.yaml

Following https://rust-gpu.github.io/blog/transition-announcement/

Update rust-gpu repository
